name: "Terraform-aks GitHub Actions"

on:
  push:
    branches:
      - "config-files"

jobs:
  terraform:
    name: "Terraform Init"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          ref: "config-files"

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v1

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: "Terraform Initialization"
        id: init
        run:  terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate