name: Deploy and configure Kubernetes in Azure with Terraform

on:
  push:
    branches:
    - main

jobs:
  setup-install:
    name: Setup, Install
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az account show
          az storage -h
    
    - name: Install Terraform  
      run: |-
        curl -O https://releases.hashicorp.com/terraform/1.1.4/terraform_1.1.4_linux_amd64.zip  

        unzip terraform_1.1.4_linux_amd64.zip
    
    - name: Terraform Init 
      run: |-
        terraform init

    - name: Terraform Validate
      run: |-
        terraform Validate

    - name: Terraform Plan
      run: |-
        terraform plan

    - name: Terraform Apply
      run: |-
        terraform apply --auto-approve